server:
  port: 8888
#  ssl:
#    enabled: true
#    key-alias: tomcat
#    key-store: D:/develop/keystore/tomcat.keystore
#    key-store-password: yangweifeng
#    key-store-type: JKS
wx:
  mp:
    configs:
      - appId: wx91a1af711a50b4d7
        secret: cff44374b44ef6166025f47d5bb5d559
        token: yangweifeng
        aesKey: